saprot_config_path: C:\czx\Project\Grade0\recommender_system_project\protein-ligand-recommender\models\SaProt_1.3B_AFDB_OMG_NCBI
saprot_output_dim: 2560
chemberta_model_name: DeepChem/ChemBERTa-77M-MLM
chemberta_hidden_dim: 384
ligand_output_dim: 2560
temperature: 0.05
max_temperature: 0.08
temperature_decay: 5.0e-05
hard_neg_margin: 1.0
num_neg_samples: 8
pos_threshold: 6.0
lr: 1.0e-05
weight_decay: 0.05
dropout_prob: 0.2
local_files_only: false
use_hard_neg_weight: true
hard_neg_weight: 1.5
use_contrastive_reg: true
reg_weight: 0.01
